
        1 +name: Android CI(release)



        3 +on:

        4 +  workflow_dispatch:

        5 + 

        6 +jobs:

        7 +  build:

        8 +    name: Build release apk

        9 +    runs-on: ubuntu-latest

       10 +    steps:

       11 +      - uses: actions/checkout@v3.0.2

       12 + 

       13 +      - name: set up JDK 11

       14 +        uses: actions/setup-java@v3.3.0

       15 +        with:

       16 +          java-version: 11

       17 +          distribution: adopt

       18 +          cache: gradle

       19 + 

       20 +      - name: Grant execute permission for gradlew

       21 +        run: chmod +x gradlew

       22 + 

       23 +      - name: Validate Gradle wrapper

       24 +        uses: gradle/wrapper-validation-action@v1.0.4

       25 + 

       26 +      - name: Build with gradle

       27 +        uses: gradle/gradle-build-action@v2.1.5

       28 +        with:

       29 +          arguments: assembleRelease

       30 +      

       31 +      - name: Upload release apk

       32 +        uses: actions/upload-artifact@v3

       33 +        with:

       34 +          name: app-release.apk

       35 +          path: app/build/outputs/apk/release/
